//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the TemporalActivityGen source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591 // publicly visible type or member must be documented

